### ISSUE TITLE
Can not select text on the screen

### ISSUE THREAD

**Issue by ruslantalpa** [subzerocloud/devtools#4]
It's useful to be able to select queries in the log output, it's not possible now

**Comment by steve-chavez** [comment]
Related to https://github.com/chjj/blessed/issues/159.

**Comment by steve-chavez** [comment]
Actually is not that, when removing this [lines](https://github.com/subzerocloud/devtools/blob/master/dashboard.jsx#L251-L261) from topMenuStyle(somehow not listening to any of ```(clickable/keyable/input): false```) and then removing the ```mouse``` attr in the log style [here](https://github.com/subzerocloud/devtools/blob/master/dashboard.jsx#L272) now it's possible to select/copy text. So seems is not a clipboard issue with the terminal but maybe a focus issue.
